### ISSUE TITLE
Solution export to vtk ASCII lacks precision

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/prepost-gui#150]
Reported by Rich

**Comment by kskinoue0612** [comment]
I understand that this is a problem when user wants to export calculation results with big X, Y values, like data in UTM coordinates.

I knew this issue, but this is not easy to fix, I think. The reason is that we use VTK classes to export data, like vtkStructuredGridWriter, and those classes do not have option about changing precision. Maybe we can modify those classes and bundle **modified** VTK dlls with iRIC, but personally I do not like that idea.

iRIC has option to export vtk BINARY files, and BINARY files have no issue about precision, I guess.
Maybe Rich wants to use VTK files to load calculation results from python scripts, and in that case, I think vtk BINARY files can help.

Scott, did you hear from Rich, about how he wants to use the vtk ASCII files?

**Comment by scharlton2** [comment]
Yes, I don't like modifying VTK source code either.  It looks like it may have been fixed in [v8.0.1](https://github.com/Kitware/VTK/commit/47248b0d194a299e35c67af890fa350121e343c2) but that's a ways away from what we're using (v6.1.0).  Maybe we can use the XML writer?

I don't know how Rich is using the vtk ASCII files, but I'll ask him when I see him.

**Comment by kskinoue0612** [comment]
Hi Scott,

Wow, VTK is now v8.0.1 !? Thats so far away.
I think we should migrate VTK someday, but not now. :-)

Maybe it is a good idea to use XML writer.
The link you've mentioned suggest that the precision that vtkXMLWriter adopt is 11, and it will be enough for most cases.

So I think adding "VTK XML" as an option to export calculation result, is a good solution.

Anyway, please say hello to Rich!

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I finally talked with Rich, and we tested using the XML writer and it worked fine.  So, I think we should just add the VTK StructuredGrid Files(*.vts) and VTK UnstructuredGrid Files(*.vtu) to the list of exportable calculation results.

Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

I close this issue, because I added a new issue #161 .
