### ISSUE TITLE
Make chart window to draw chart from cell center calculation result

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#224]

**Comment by scharlton2** [comment]
Hi Keisuke,

Here is what I'm thinking about doing for drawing charts with cell center results.  It seems to be necessary to not be able to mix vertex scalars with cell-centered scalars since the indices will be different.  Let me know what you think about doing it this way or if you have some other ideas.

Thanks,
Scott


![image](https://user-images.githubusercontent.com/7538707/36518932-d7265868-1745-11e8-95dc-0a851dd5aac6.png)



![image](https://user-images.githubusercontent.com/7538707/36518943-ede60012-1745-11e8-8371-4da6c4cc9f49.png)


![image](https://user-images.githubusercontent.com/7538707/36519097-b0faddac-1746-11e8-9364-9907267d935c.png)

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for sharing you idea about the interface.
I agree that it will be good to add ComboBox to switch GridLocation.

Let me comment about where to add the ComboBox.

Solver output calculation result defined not only at grid nodes or grid cells, but one value defined at each time step. It is called "Point data". For example discharge. Please look at the dialog below.

![datasource_current](https://user-images.githubusercontent.com/4031569/36521636-143cc102-17db-11e8-9ad6-02a831b9f526.png)

To support such cases, I propose that we add the combobox just under "Two dimensional Data" label, like below.

![datasource_updated](https://user-images.githubusercontent.com/4031569/36521642-19cddfc0-17db-11e8-8b14-72f594002738.png)

I welcome proposals about other dialog designs.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I found a couple of bugs with pull request #278.  I'm working on some test solvers to make sure that everything is working right (mostly 3-D).  So, I reopened this issue and will call the next branch 
issue-278-2.  I'll leave #278 merged in since it looks like your pull request #280 depends on it.

Thanks,
Scott
