### ISSUE TITLE
Opening *.ipro file and saving with a new name and reopening that file causes lock-up

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/prepost-gui#285]
Opening an *.ipro file containing results and saving it with a new name saves a copy of "Case1.cgn.lock" within the zip file.  This seems to only occur for the first file opened within i-RIC.  I verified this using both Release and Debug modes.  Placing breakpoints on both the ctor and the dtor of FileLocker shows that one of the dtor is not called until a new file is opened or i-RIC is closed.

To reproduce:

0. If you have "solver_test1" in your list of solvers, remove it so that you open the file in "Post Only" mode.

1. Start i-RIC and open any file within [test_projects_issue-224.zip](https://github.com/i-RIC/prepost-gui/files/1801810/test_projects_issue-224.zip).

2. Open workspace directory (for example C:\Users\charlton\.iRIC_workspace\d58a40d7f96213c2ac63dfdae95cf660) and verify that it contains "Case1.cgn.lock".

3. File->Save As File(*.ipro) (for example test_vertex_xxx.ipro)

4. Open that file with a program such as 7-Zip and verify that it contains "Case1.cgn.lock".

5. Open any other file in i-RIC.

6. Open the previous file test_vertiex_xxx.ipro and verify that i-RIC becomes unresponsive.

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for reporting this.
I've tried to reproduce this issue in my environment, but 4. did not occur on my environment.
I mean, Case1.cgn.lock was not in the new *.ipro file.

Maybe this issue does not occur every time, or is dependent on environment.

I feel this is a major issue, because when it occurs, iRIC GUI becomes unresponsive.

If it is possible to reproduce this issue on your environment, can I ask you to fix this?

I'm afraid maybe it is not so easy to fix this issue. If in that case, please let me know, and share information about the situation.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

No problem, I'll let you know what I find.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Thanks, Scott!

 Keisuke,

**Comment by scharlton2** [comment]
Hi Keisuke,

I think Rich and I figured out why you were unable to reproduce on your environment.  It seems this problem only occurs when you are running in "Post Only" mode.  I've updated the steps to reproduce the problem.  If you have the time, could you please upload your "solver_test1" solver folder?

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

I've tested again after removing "solver_test1", and the the issue was reproducible on my environment.

I feel I'm responsible for this issue, so I'll look into this.

Thanks,
Keisuke
