### ISSUE TITLE
CGNS file extension should be changed to "*.cgns", not "*.cgn".

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#297]
Currently CGNS files are saved with extension "*.cgn", but should change to "*.cgns".

Some tools do not recognize files with "*.cgn" as CGNS files, so this will improve user experience.

**Comment by scharlton2** [comment]
Hi Keisuke,

This doesn't seem to be fully implemented.   See email dated 2018-04-18 that you sent to me from your gmail account.  The cgns file is still called "Case1.cgn" instead of "Case1.cgns".  At least the following two routines need to be updated:

`QString ProjectData::workCgnsFileName(const QString& name) const`

and

`bool ProjectMainFile::loadCgnsFile(const QString& name)`

Thanks,
Scott
