### ISSUE TITLE
v3.0 Cross section line draw 

### ISSUE THREAD

**Issue by kazutake** [i-RIC/prepost-gui#37]
Different way is used to draw the cross sectional line between it is on main window and on cross sectional windows. It is hard to find out what is correct. For example, color means different year data. Green line in the left side is highest on main window, but Red line is the highest on cross sectional window.

![image](https://cloud.githubusercontent.com/assets/7007415/21189767/185a869e-c263-11e6-84c3-dc8112892452.png)

**Comment by kskinoue0612** [comment]
Currently, line color of cross section can be setup independently on Pre-Processor Window and Cross Section Window. When you setup color for each data the same on Pre-Processor Window and on Cross Section Windows, it will be easy to distinguish data.

Or maybe we can make modify iRIC GUI so that Pre-processor window and Cross Section window refers the same color setting for each data.

**Comment by kazutake** [comment]
Please tell the status.

**Comment by kskinoue0612** [comment]
Hi Scott,

You can use the following files to test if it is fixed.

[rivdata.zip](https://github.com/i-RIC/prepost-gui/files/1548052/rivdata.zip)
